# SPDX-License-Identifier: Apache-2.0
"""Generate the schematic candidate; dimensions are micrometres, not layout."""
from dataclasses import dataclass, asdict
from pathlib import Path
import json


@dataclass(frozen=True)
class Design:
    resistor_megohm: int = 300
    buffer_stack: int = 8
    stages: int = 7
    timing_gate_length_um: float = 10.0

    def validate(self):
        if not 1 <= self.resistor_megohm <= 300:
            raise ValueError("resistor_megohm must be 1..300")
        if not 1 <= self.buffer_stack <= 16:
            raise ValueError("buffer_stack must be 1..16")
        if self.stages not in (3, 5, 7):
            raise ValueError("stages must be 3, 5 or 7")
        if not .28 <= self.timing_gate_length_um <= 10:
            raise ValueError("timing_gate_length_um must be .28..10")


def fet(name, drain, gate, source, bulk, p=False, w=1.0, l=2.0):
    # Conservative explicit diffusion estimates; replace with extracted values.
    return (f"X{name} {drain} {gate} {source} {bulk} "
            f"{'pmos' if p else 'nmos'}_3p3 w={w:g}u l={l:g}u "
            f"ad={w * .5:g}p as={w * .5:g}p "
            f"pd={2 * (w + .5):g}u ps={2 * (w + .5):g}u\n")


def netlist(d=Design()):
    d.validate()
    s = """* SPDX-License-Identifier: Apache-2.0
* RISCay-MCU GF180 low-power oscillator SCHEMATIC CANDIDATE, not qualified IP.
* Derived from Tim Edwards/Efabless sky130_ef_ip__rc_osc_500k architecture.
* See NOTICE.md and upstream/LICENSE. Substantial modifications: GF180 3.3V,
* beta-multiplier bias, POR-assisted startup, configurable ring, stacked buffer.
* Generated by design.py. No ideal current sources, resistors or timing caps.
* rst_n must stay LOW during power ramp and >= 5 ms after supply is valid.
* Reset actively starts the bias; it is NOT a low-current shutdown control.
* Clock output is forced LOW in reset. Supply is the only power-off control.
.subckt riscay_lf_osc_gf180 vdd vss rst_n clk
"""
    s += fet("reset_p", "rst", "rst_n", "vdd", "vdd", True, l=1)
    s += fet("reset_n", "rst", "rst_n", "vss", "vss", l=1)
    s += "* Self-biased current reference. N ratio 4:1, matched P mirror.\n"
    s += fet("ref_p", "nbias", "pbias", "vdd", "vdd", True)
    s += fet("ref_pd", "pbias", "pbias", "vdd", "vdd", True)
    s += fet("ref_nd", "nbias", "nbias", "vss", "vss")
    s += fet("ref_n4", "pbias", "nbias", "rtop", "vss", w=4)
    for k in range(10):
        hi = "rtop" if k == 0 else f"res{k}"
        lo = "vss" if k == 9 else f"res{k+1}"
        s += f"XR{k} {hi} {lo} vss ppolyf_u_3k r_width=1u r_length={d.resistor_megohm*31.812:g}u\n"
    s += "* POR removes the beta multiplier's zero-current equilibrium.\n"
    s += fet("startup", "pbias", "rst", "vss", "vss", w=.22, l=10)
    s += "* Current-starved ring: explicit slow timing nodes, common bias.\n"
    for k in range(d.stages):
        inp, out = f"r{(k-1)%d.stages}", f"r{k}"
        s += fet(f"ps{k}", f"ps{k}", "pbias", "vdd", "vdd", True)
        s += fet(f"p{k}", out, inp, f"ps{k}", "vdd", True, l=1)
        s += fet(f"n{k}", out, inp, f"ns{k}", "vss", l=1)
        s += fet(f"ns{k}", f"ns{k}", "nbias", "vss", "vss")
        # A real 3.3 V NMOS wired as a gate capacitor. No ideal C, MIM option,
        # or behavioral capacitance-model substitution is used.
        s += fet(f"timing{k}", "vss", out, "vss", "vss", w=10, l=d.timing_gate_length_um)
    s += fet("park", "r0", "rst", "vss", "vss", l=1)
    s += "* Weak stacked inverter reduces crowbar current from slow ring edges.\n"
    for k in range(d.buffer_stack):
        drain = "q" if k == 0 else f"bp{k}"
        source = "vdd" if k == d.buffer_stack - 1 else f"bp{k+1}"
        s += fet(f"bufp{k}", drain, "r0", source, "vdd", True, w=.44, l=50)
        drain = "q" if k == 0 else f"bn{k}"
        source = "vss" if k == d.buffer_stack - 1 else f"bn{k+1}"
        s += fet(f"bufn{k}", drain, "r0", source, "vss", w=.22, l=50)
    s += "* Intermediate buffer sharpens edges before the stronger clock driver.\n"
    s += fet("midp", "mid", "q", "vdd", "vdd", True, w=.44, l=5)
    s += fet("midn", "mid", "q", "vss", "vss", w=.22, l=5)
    # NAND(mid, rst_n), followed by inverter. Qualifies output low during POR.
    s += fet("gatep1", "gated", "mid", "vdd", "vdd", True, w=1, l=.28)
    s += fet("gatep2", "gated", "rst_n", "vdd", "vdd", True, w=1, l=.28)
    s += fet("gaten1", "gated", "mid", "gn", "vss", w=1, l=.28)
    s += fet("gaten2", "gn", "rst_n", "vss", "vss", w=1, l=.28)
    s += fet("outp", "clk", "gated", "vdd", "vdd", True, w=2, l=.28)
    s += fet("outn", "clk", "gated", "vss", "vss", l=.28)
    return s + ".ends riscay_lf_osc_gf180\n"


if __name__ == "__main__":
    base = Path(__file__).resolve().parent
    design = Design()
    (base / "riscay_lf_osc_gf180.spice").write_text(netlist(design), newline="\n")
    (base / "candidate.json").write_text(json.dumps(asdict(design), indent=2) + "\n", newline="\n")
